me: deeplearn_course

channels:

  - pytorch # DL
  - https://conda.anaconda.org/rdkit # Molecule
  - dglteam # DGL
  - https://conda.anaconda.org/conda-forge/

dependencies:

  # basic
  - python=3.6
  - numpy
  - mkl
  - ipython
  - jupyter
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - networkx
  - seaborn
  - scikit-image
  - tqdm
  - ipdb
  - imgaug

  - pytorch=1.1 # DL
  - rdkit # Molecule
  - dgl=0.3 # DGL

  - pip:
    - torchvision # DL
    - gym # RL
    - tensorboardx # TSP
    - fastprogress # TSPi
    - pytorch-pretrained-bert>=0.6.2
    - wikipedia
    - boto3
    - torch>=0.4.1
